[package]
name = "jsondb"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 1
lto = "off"

[dependencies]
env_logger = "*"
log = "*"
openssl = "*"
actix-web = { version = "*", features = ["openssl"] }
awc = { version = "*", features = ["openssl"] }
serde_json = "*"
regex = "*"
