[package]
name = "jsondb"
version = "0.0.1"
edition = "2018"

[profile.dev]
opt-level = 1
lto = "off"

[dependencies]
env_logger = "*"
log = "*"
awc = "*"
rustls-pemfile = "*"
actix-web = { version = "*", features = ["rustls"] }
rustls = "0.20.8"
serde = "*"
serde_json = "*"
regex = "*"
